### ISSUE TITLE
cryptiles security vulnerability

### ISSUE THREAD

**Issue by kaburkett** [w-w-wood-products-inc/mozaik-themes-extra#14]
GitHub security bot opened an alert for cryptiles:

https://github.com/w-w-wood-products-inc/mozaik-themes-extra/network/alert/yarn.lock/cryptiles/open

The bot is unable to resolve this automatically.

**Comment by abaga129** [comment]
Remediation

Upgrade cryptiles to version 4.1.2 or later. For example:

```
cryptiles@^4.1.2:
  version "4.1.2"
```

**Comment by kaburkett** [comment]
closed by #21
