### ISSUE TITLE
braces security vulnerability

### ISSUE THREAD

**Issue by kaburkett** [w-w-wood-products-inc/mozaik-themes-extra#15]
GitHub security bot opened an alert for braces:

https://github.com/w-w-wood-products-inc/mozaik-themes-extra/network/alert/yarn.lock/braces/open

The vulnerability bot was unable to automatically resolve this vulnerability.

**Comment by abaga129** [comment]
Upgrade braces to version 2.3.1 or later. For example:

```
braces@^2.3.1:
  version "2.3.1"

```
